import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header/page";
import Footer from "./footer/page";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Explore Sourav Das' portfolio showcasing web development skills in React.js, Next.js, and JavaScript.",
  applicationName: "Sourav Das Portfolio",
  keywords: [
    "Sourav Das",
    "Front-End Developer",
    "React.js",
    "Next.js",
    "JavaScript",
    "Portfolio",
  ],
  openGraph: {
    title: "Portfolio",
    description: "Explore Sourav Das' portfolio showcasing web development skills in React.js, Next.js, and JavaScript.",
    url: "https://portfolio-new-five-eosin.vercel.app/",
    siteName: "Sourav Das Portfolio",
    images: [
      {
        url: "https://portfolio-new-five-eosin.vercel.app/image/1741623665154.jpg",
        width: 1200,
        height: 630,
        alt: "Portfolio",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Portfolio",
    description: "Explore Sourav Das' portfolio showcasing web development skills in React.js, Next.js, and JavaScript.",
    images: ["https://portfolio-new-five-eosin.vercel.app/image/1741623665154.jpg"],
  },
  metadataBase: new URL("https://portfolio-new-five-eosin.vercel.app"),
  robots: "index, follow",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
